ollama pull mistral:7b 
ollama pull gemma:7b 
ollama pull gemma2:9b 
ollama pull gemma3:4b 
ollama pull llama3.1:8b
ollama pull qwen2.5:7b 
ollama pull phi4:14b 
ollama pull mistral-nemo:12b 
ollama pull llama2:7b 
ollama pull deepseek-r1:8b